language: java

jdk:
  - oraclejdk7
  - oraclejdk8

install: 
   - ./libs/gson/create_enterprisecoding_gson.sh
   - mvn install -DskipTests=true
script: mvn test

notifications:
  email: false

sudo: false

cache:
  directories:
    - $HOME/.m2
